services:
  - type: worker
    name: crypto-signal-bot
    env: python
    plan: free
    buildCommand: |
        pip install --upgrade pip
        pip install -r requirements.txt
    startCommand: python crypto_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
