services:
  - type: worker
    name: crypto-signal-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python crypto_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token_here
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here
